name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Enforce no_std
      run: |
        # Add a target without std
        rustup target add thumbv7em-none-eabi
        # Verify that lib.rs compiles strictly without std
        cargo check --target thumbv7em-none-eabi --no-default-features
